In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df=pd.read_csv(url)
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

**retreiving colunms**

In [3]:
df["sex"]

0      Female
1        Male
2        Male
3        Male
4      Female
        ...
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: str

In [4]:
df[["sex","size"]]

        sex  size
0    Female     2
1      Male     3
2      Male     3
3      Male     2
4    Female     4
..      ...   ...
239    Male     3
240  Female     2
241    Male     2
242    Male     2
243  Female     2

[244 rows x 2 columns]

**Retreiving row**

loc[row,columns]  row in number and column by its name

In [6]:
df.loc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [8]:
df.loc[0,["sex","size"]]

sex     Female
size         2
Name: 0, dtype: object

In [12]:
df.loc[0:3,["sex","tip","size","day"]]

      sex   tip  size  day
0  Female  1.01     2  Sun
1    Male  1.66     3  Sun
2    Male  3.50     3  Sun
3    Male  3.31     2  Sun

.iloc[row,column] both row and columns are strictly in index

In [7]:
df.iloc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [11]:
df.iloc[0,5]

'Dinner'

In [14]:
df.iloc[3:7,1:4]

    tip     sex smoker
3  3.31    Male     No
4  3.61  Female     No
5  4.71    Male     No
6  2.00    Male     No

**.at[row,col] and .iat[row,col]** are optimized for finding a specific element

In [17]:
df.at[0,"day"]

'Sun'

In [18]:
df.iat[3,5]

'Dinner'

**filtering with coditions**

In [22]:
df[df["tip"]>1.5]

     total_bill   tip     sex smoker   day    time  size
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[218 rows x 7 columns]

In [26]:
df[(df["size"]>3) & (df["tip"]>1.6)]

     total_bill   tip     sex smoker   day    time  size
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
13        18.43  3.00    Male     No   Sun  Dinner     4
23        39.42  7.58    Male     No   Sat  Dinner     4
25        17.81  2.34    Male     No   Sat  Dinner     4
31        18.35  2.50    Male     No   Sat  Dinner     4
33        20.69  2.45  Female     No   Sat  Dinner     4
44        30.40  5.60    Male     No   Sun  Dinner     4
47        32.40  6.00    Male     No   Sun  Dinner     4
52        34.81  5.20  Female     No   Sun  Dinner     4
54        25.56  4.34    Male     No   Sun  Dinner     4
56        38.01  3.00    Male    Yes   Sat  Dinner     4
59        48.27  6.73    Male     No   Sat  Dinner     4
63        18.29  3.76    Male    Yes   Sat  Dinner     4
77        27.20  4.00    Male     No  Thur   Lunch     4
85        34.83  5.17  Female     No  Thur   Lunch     4
95        40.17  4.73    Male    Yes   Fri  Dinner     4
116       29.93  5.07    Male     No   Sun  Dinner     4
119       24.08  2.92  Female     No  Thur   Lunch     4
125       29.80  4.20  Female     No  Thur   Lunch     6
141       34.30  6.70    Male     No  Thur   Lunch     6
142       41.19  5.00    Male     No  Thur   Lunch     5
143       27.05  5.00  Female     No  Thur   Lunch     6
153       24.55  2.00    Male     No   Sun  Dinner     4
154       19.77  2.00    Male     No   Sun  Dinner     4
155       29.85  5.14  Female     No   Sun  Dinner     5
156       48.17  5.00    Male     No   Sun  Dinner     6
157       25.00  3.75  Female     No   Sun  Dinner     4
159       16.49  2.00    Male     No   Sun  Dinner     4
160       21.50  3.50    Male     No   Sun  Dinner     4
167       31.71  4.50    Male     No   Sun  Dinner     4
180       34.65  3.68    Male    Yes   Sun  Dinner     4
183       23.17  6.50    Male    Yes   Sun  Dinner     4
185       20.69  5.00    Male     No   Sun  Dinner     5
187       30.46  2.00    Male    Yes   Sun  Dinner     5
197       43.11  5.00  Female    Yes  Thur   Lunch     4
204       20.53  4.00    Male    Yes  Thur   Lunch     4
207       38.73  3.00    Male    Yes   Sat  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
212       48.33  9.00    Male     No   Sat  Dinner     4
216       28.15  3.00    Male    Yes   Sat  Dinner     5
219       30.14  3.09  Female    Yes   Sat  Dinner     4
227       20.45  3.00    Male     No   Sat  Dinner     4
230       24.01  2.00    Male    Yes   Sat  Dinner     4

In [30]:
df[(df["sex"]=="male") | (df["smoker"]=="Yes") & (df["size"]>4)]

     total_bill  tip   sex smoker  day    time  size
187       30.46  2.0  Male    Yes  Sun  Dinner     5
216       28.15  3.0  Male    Yes  Sat  Dinner     5

**Querying with .query()**

In [31]:
df.query("size>1")

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[240 rows x 7 columns]

In [32]:
# use and , or instead of & , |
df.query("size>4 and tip<4")

     total_bill  tip   sex smoker  day    time  size
187       30.46  2.0  Male    Yes  Sun  Dinner     5
216       28.15  3.0  Male    Yes  Sat  Dinner     5

In [38]:
df.query("size>4 and tip<4 or sex=='Male'")

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [46]:
# circular query
df.query("3>tip<=7")

     total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
6          8.77  2.00    Male     No  Sun  Dinner     2
8         15.04  1.96    Male     No  Sun  Dinner     2
10        10.27  1.71    Male     No  Sun  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
236       12.60  1.00    Male    Yes  Sat  Dinner     2
237       32.83  1.17    Male    Yes  Sat  Dinner     2
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[123 rows x 7 columns]

In [47]:
df.query("3>tip<=7 and size>3")

     total_bill   tip     sex smoker   day    time  size
25        17.81  2.34    Male     No   Sat  Dinner     4
31        18.35  2.50    Male     No   Sat  Dinner     4
33        20.69  2.45  Female     No   Sat  Dinner     4
119       24.08  2.92  Female     No  Thur   Lunch     4
153       24.55  2.00    Male     No   Sun  Dinner     4
154       19.77  2.00    Male     No   Sun  Dinner     4
159       16.49  2.00    Male     No   Sun  Dinner     4
187       30.46  2.00    Male    Yes   Sun  Dinner     5
230       24.01  2.00    Male    Yes   Sat  Dinner     4

In [45]:
#using variable inside query by making f string 
var="smoker"
var2="day"
df.query(f"{var}=='Yes' and {var2}=='Sat'")

     total_bill    tip     sex smoker  day    time  size
56        38.01   3.00    Male    Yes  Sat  Dinner     4
58        11.24   1.76    Male    Yes  Sat  Dinner     2
60        20.29   3.21    Male    Yes  Sat  Dinner     2
61        13.81   2.00    Male    Yes  Sat  Dinner     2
62        11.02   1.98    Male    Yes  Sat  Dinner     2
63        18.29   3.76    Male    Yes  Sat  Dinner     4
67         3.07   1.00  Female    Yes  Sat  Dinner     1
69        15.01   2.09    Male    Yes  Sat  Dinner     2
72        26.86   3.14  Female    Yes  Sat  Dinner     2
73        25.28   5.00  Female    Yes  Sat  Dinner     2
76        17.92   3.08    Male    Yes  Sat  Dinner     2
102       44.30   2.50  Female    Yes  Sat  Dinner     3
103       22.42   3.48  Female    Yes  Sat  Dinner     2
105       15.36   1.64    Male    Yes  Sat  Dinner     2
106       20.49   4.06    Male    Yes  Sat  Dinner     2
107       25.21   4.29    Male    Yes  Sat  Dinner     2
109       14.31   4.00  Female    Yes  Sat  Dinner     2
168       10.59   1.61  Female    Yes  Sat  Dinner     2
169       10.63   2.00  Female    Yes  Sat  Dinner     2
170       50.81  10.00    Male    Yes  Sat  Dinner     3
171       15.81   3.16    Male    Yes  Sat  Dinner     2
206       26.59   3.41    Male    Yes  Sat  Dinner     3
207       38.73   3.00    Male    Yes  Sat  Dinner     4
208       24.27   2.03    Male    Yes  Sat  Dinner     2
209       12.76   2.23  Female    Yes  Sat  Dinner     2
210       30.06   2.00    Male    Yes  Sat  Dinner     3
211       25.89   5.16    Male    Yes  Sat  Dinner     4
213       13.27   2.50  Female    Yes  Sat  Dinner     2
214       28.17   6.50  Female    Yes  Sat  Dinner     3
215       12.90   1.10  Female    Yes  Sat  Dinner     2
216       28.15   3.00    Male    Yes  Sat  Dinner     5
217       11.59   1.50    Male    Yes  Sat  Dinner     2
218        7.74   1.44    Male    Yes  Sat  Dinner     2
219       30.14   3.09  Female    Yes  Sat  Dinner     4
229       22.12   2.88  Female    Yes  Sat  Dinner     2
230       24.01   2.00    Male    Yes  Sat  Dinner     4
231       15.69   3.00    Male    Yes  Sat  Dinner     3
234       15.53   3.00    Male    Yes  Sat  Dinner     2
236       12.60   1.00    Male    Yes  Sat  Dinner     2
237       32.83   1.17    Male    Yes  Sat  Dinner     2
240       27.18   2.00  Female    Yes  Sat  Dinner     2
241       22.67   2.00    Male    Yes  Sat  Dinner     2

In [49]:
# use @ for usina global variable inside " "
bill=18
df.query("total_bill> @bill")

     total_bill   tip     sex smoker   day    time  size
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
7         26.88  3.12    Male     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[117 rows x 7 columns]