**Data Cleaning and Preprocessing**

In [3]:
import pandas as pd

In [33]:

df=pd.read_csv("dataset/Diabetes Missing Data.csv")
df

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

**checking for missing data**

In [11]:
df.isnull()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,False,False,False,False,True,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,True,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,True,True,False,False,False,False
767,False,False,False,False,True,False,False,False,False

In [14]:
df.isnull().sum()

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

**drop missing data**

In [16]:
df.dropna()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
6,3,78.0,50.0,32.0,88.0,31.0,0.248,26,1
8,2,197.0,70.0,45.0,543.0,30.5,0.158,53,1
13,1,189.0,60.0,23.0,846.0,30.1,0.398,59,1
...,...,...,...,...,...,...,...,...,...
753,0,181.0,88.0,44.0,510.0,43.3,0.222,26,1
755,1,128.0,88.0,39.0,110.0,36.5,1.057,37,1
760,2,88.0,58.0,26.0,16.0,28.4,0.766,22,0
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0

In [17]:
df.dropna(axis=1)

     Pregnant  Diabetes_Pedigree  Age  Class
0           6              0.627   50      1
1           1              0.351   31      0
2           8              0.672   32      1
3           1              0.167   21      0
4           0              2.288   33      1
..        ...                ...  ...    ...
763        10              0.171   63      0
764         2              0.340   27      0
765         5              0.245   30      0
766         1              0.349   47      1
767         1              0.315   23      0

[768 rows x 4 columns]

**fill missing data**

In [63]:
data=pd.read_csv("dataset/data_cleaning.csv")
data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [20]:
data.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [21]:
data.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [22]:
data.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [29]:
df2=data["Age"].fillna(df["Age"].mean()).copy
df2

<bound method NDFrame.copy of 0    25.000000
1    33.240885
2    30.000000
3    33.240885
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    33.240885
Name: Age, dtype: float64>

In [30]:
data.fillna(5)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   5.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   5.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        5  28.0        Delhi      F     eve@domain.com           5
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   5.0        Delhi      M    charlie@example  20-07-2021

In [34]:
df["Age"]=df["Age"].astype("int32")
df

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [35]:
data.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [38]:
data.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [40]:
data.duplicated(subset=["Name","Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [43]:
data.duplicated(subset=["Gender"])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8     True
dtype: bool

In [47]:
df3=data["Name"].str.lower()
df3

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: str

In [52]:
data["City"].str.contains("New York" , case="false")

0     True
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8    False
Name: City, dtype: bool

In [64]:
data["Email"].str.split('@')

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [68]:
data["Email"].str.split('@')[0:4]

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
Name: Email, dtype: object

In [75]:
data.fillna(df["Age"].mean())

        Name        Age         City Gender              Email   Join Date
0      Alice  25.000000     New York      F  alice@example.com  01-05-2021
1    Charlie  33.240885        Delhi      M    charlie@example  20-07-2021
2        Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3    Charlie  33.240885        Delhi      M    charlie@example  20-07-2021
4      David  22.000000       Mumbai      M  david@example.com  12-11-2019
5  33.240885  28.000000        Delhi      F     eve@domain.com   33.240885
6      Alice  25.000000     New York      F  alice@example.com  01-05-2021
7      Alice  25.000000     New York      F  alice@example.com  01-05-2021
8    Charlie  33.240885        Delhi      M    charlie@example  20-07-2021

In [80]:
data["Age"] = data["Age"].fillna(data["Age"].mean())
data["Age"] = data["Age"].astype(int)

In [81]:
data

      Name  Age         City Gender              Email   Join Date
0    Alice   25     New York      F  alice@example.com  01-05-2021
1  Charlie   25        Delhi      M    charlie@example  20-07-2021
2      Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   25        Delhi      M    charlie@example  20-07-2021
4    David   22       Mumbai      M  david@example.com  12-11-2019
5      NaN   28        Delhi      F     eve@domain.com         NaN
6    Alice   25     New York      F  alice@example.com  01-05-2021
7    Alice   25     New York      F  alice@example.com  01-05-2021
8  Charlie   25        Delhi      M    charlie@example  20-07-2021

In [82]:
data["Age group"]=data["Age"].apply(lambda x : "Adult" if x>25 else "Minor")

In [83]:
data

      Name  Age         City Gender              Email   Join Date Age group
0    Alice   25     New York      F  alice@example.com  01-05-2021     Minor
1  Charlie   25        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   25        Delhi      M    charlie@example  20-07-2021     Minor
4    David   22       Mumbai      M  david@example.com  12-11-2019     Minor
5      NaN   28        Delhi      F     eve@domain.com         NaN     Adult
6    Alice   25     New York      F  alice@example.com  01-05-2021     Minor
7    Alice   25     New York      F  alice@example.com  01-05-2021     Minor
8  Charlie   25        Delhi      M    charlie@example  20-07-2021     Minor

In [88]:
data["Gender"]=data["Gender"].replace({"M" : "Male","F" : "Female"})
data

      Name  Age         City  Gender              Email   Join Date Age group
0    Alice   25     New York  Female  alice@example.com  01-05-2021     Minor
1  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Minor
2      Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Minor
4    David   22       Mumbai    Male  david@example.com  12-11-2019     Minor
5      NaN   28        Delhi  Female     eve@domain.com         NaN     Adult
6    Alice   25     New York  Female  alice@example.com  01-05-2021     Minor
7    Alice   25     New York  Female  alice@example.com  01-05-2021     Minor
8  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Minor

In [ ]:
map_data={"Mumbai":"New Mumbai","Delhi":"NEw Dilhi}
data["City"]=data["City"].map{