In [37]:
import pandas as pd

In [38]:
df=pd.read_csv("dataset/data2.csv")
df

       name  aptitude  interview  DSA  project  skills
0  abhishek        10         10   10       10      10
1     sneha         1          5    2        6       4
2    barsha         8          9    8        9       7
3      amit         6          9    5        7       5
4   anshika         8          6    2        6       2
5     kirti         5          5    6        5       6
6     rahul         6          2    3        4       4
7    ishika         2          7    5        6       6

**sorting rows**

In [39]:
# ont the basis of the value of aptitude column
# ascending = False means decreasing order
df.sort_values("aptitude",ascending=False)

       name  aptitude  interview  DSA  project  skills
0  abhishek        10         10   10       10      10
2    barsha         8          9    8        9       7
4   anshika         8          6    2        6       2
3      amit         6          9    5        7       5
6     rahul         6          2    3        4       4
5     kirti         5          5    6        5       6
7    ishika         2          7    5        6       6
1     sneha         1          5    2        6       4

In [40]:
# sorts on the basis of aptitude and if clash happens then it will chwck DSA
df.sort_values(["aptitude","DSA"],ascending=False)

       name  aptitude  interview  DSA  project  skills
0  abhishek        10         10   10       10      10
2    barsha         8          9    8        9       7
4   anshika         8          6    2        6       2
3      amit         6          9    5        7       5
6     rahul         6          2    3        4       4
5     kirti         5          5    6        5       6
7    ishika         2          7    5        6       6
1     sneha         1          5    2        6       4

In [41]:
df2=df.sort_values(["DSA","interview"],ascending=False)
df2

       name  aptitude  interview  DSA  project  skills
0  abhishek        10         10   10       10      10
2    barsha         8          9    8        9       7
5     kirti         5          5    6        5       6
3      amit         6          9    5        7       5
7    ishika         2          7    5        6       6
6     rahul         6          2    3        4       4
4   anshika         8          6    2        6       2
1     sneha         1          5    2        6       4

In [21]:
# this will sort the new rearranged index
df2.sort_index()

       name  aptitude  interview  DSA  project  skills
0  abhishek        10         10   10       10      10
1     sneha         1          5    2        6       4
2    barsha         8          9    8        9       7
3      amit         6          9    5        7       5
4   anshika         8          6    2        6       2
5     kirti         5          5    6        5       6
6     rahul         6          2    3        4       4
7    ishika         2          7    5        6       6

In [42]:
# this will add new index column while keeping the older one 
# by drop=true we can drop the older index
df2.reset_index()

   index      name  aptitude  interview  DSA  project  skills
0      0  abhishek        10         10   10       10      10
1      2    barsha         8          9    8        9       7
2      5     kirti         5          5    6        5       6
3      3      amit         6          9    5        7       5
4      7    ishika         2          7    5        6       6
5      6     rahul         6          2    3        4       4
6      4   anshika         8          6    2        6       2
7      1     sneha         1          5    2        6       4

In [43]:
df2.reset_index(inplace=True,drop=True)
df3=df2.copy()

In [44]:
df3

       name  aptitude  interview  DSA  project  skills
0  abhishek        10         10   10       10      10
1    barsha         8          9    8        9       7
2     kirti         5          5    6        5       6
3      amit         6          9    5        7       5
4    ishika         2          7    5        6       6
5     rahul         6          2    3        4       4
6   anshika         8          6    2        6       2
7     sneha         1          5    2        6       4

In [45]:
# makes a new coumns according to the rank of skills column
df3["rank_skill"]=df3["skills"].rank()
df3

       name  aptitude  interview  DSA  project  skills  rank_skill
0  abhishek        10         10   10       10      10         8.0
1    barsha         8          9    8        9       7         7.0
2     kirti         5          5    6        5       6         5.5
3      amit         6          9    5        7       5         4.0
4    ishika         2          7    5        6       6         5.5
5     rahul         6          2    3        4       4         2.5
6   anshika         8          6    2        6       2         1.0
7     sneha         1          5    2        6       4         2.5

In [46]:
# normal ranking system
df3["rank_skill"]=df3["skills"].rank(ascending=False)
df3

       name  aptitude  interview  DSA  project  skills  rank_skill
0  abhishek        10         10   10       10      10         1.0
1    barsha         8          9    8        9       7         2.0
2     kirti         5          5    6        5       6         3.5
3      amit         6          9    5        7       5         5.0
4    ishika         2          7    5        6       6         3.5
5     rahul         6          2    3        4       4         6.5
6   anshika         8          6    2        6       2         8.0
7     sneha         1          5    2        6       4         6.5

In [47]:
# method = dense gives the same rank to more then one row with same value
df3["rank_skill"]=df3["skills"].rank(ascending=False,method="dense")
df3

       name  aptitude  interview  DSA  project  skills  rank_skill
0  abhishek        10         10   10       10      10         1.0
1    barsha         8          9    8        9       7         2.0
2     kirti         5          5    6        5       6         3.0
3      amit         6          9    5        7       5         4.0
4    ishika         2          7    5        6       6         3.0
5     rahul         6          2    3        4       4         5.0
6   anshika         8          6    2        6       2         6.0
7     sneha         1          5    2        6       4         5.0

**Renaming of columns**

In [49]:

df3.rename(columns={"interview":"soft_skill"},inplace=True)
df3

       name  aptitude  soft_skill  DSA  project  skills  rank_skill
0  abhishek        10          10   10       10      10         1.0
1    barsha         8           9    8        9       7         2.0
2     kirti         5           5    6        5       6         3.0
3      amit         6           9    5        7       5         4.0
4    ishika         2           7    5        6       6         3.0
5     rahul         6           2    3        4       4         5.0
6   anshika         8           6    2        6       2         6.0
7     sneha         1           5    2        6       4         5.0

**chsanging the order of columns**

In [51]:
df3=["name","DSA","aptitude","Soft_Skill","skills","project","rank_skill"]
df3

['name', 'DSA', 'aptitude', 'Soft_Skill', 'skills', 'project', 'rank_skill']