In [9]:
import pandas as pd
data={
    "name":["Abhishek","Barsha","Ankita"],
    "gender":["male","female","female"],
    "maths":[100,78,56],
    "physics":[99,80,78],
    "chemistry":[98,88,90]
}
df=pd.DataFrame(data)

In [10]:
df

       name  gender  maths  physics  chemistry
0  Abhishek    male    100       99         98
1    Barsha  female     78       80         88
2    Ankita  female     56       78         90

**melt**

.melt(id_var=[columns staying intact],
        value_vars=[columns that are melting],
        var_name=new name to melted columns,
        value_names=column name for their value)

In [28]:
df2=df.melt(id_vars=["name","gender"],value_vars=["maths","physics","chemistry"],var_name="subject",value_name="marks")
df2

       name  gender    subject  marks
0  Abhishek    male      maths    100
1    Barsha  female      maths     78
2    Ankita  female      maths     56
3  Abhishek    male    physics     99
4    Barsha  female    physics     80
5    Ankita  female    physics     78
6  Abhishek    male  chemistry     98
7    Barsha  female  chemistry     88
8    Ankita  female  chemistry     90

**Pivot** opposite of .melt
.pivot_table(index=[],columns="  ",velues="  ")

index: The column whose unique values will become the rows of the new DataFrame.
columns: The column whose unique values will become the columns of the new DataFrame.
values: The column whose values will fill the new DataFrame. These will become the actual data (values in the table).

In [23]:
df2.pivot(index=["name","gender"],columns="subject",values="marks")

subject          chemistry  maths  physics
name     gender
Abhishek male           98    100       99
Ankita   female         90     56       78
Barsha   female         88     78       80