**Group By and Aggregation**

In [3]:
import pandas as pd

In [38]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "M", "M", "F", "F", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 80, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [25]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      M      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      F      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [26]:
df.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [27]:
df.groupby("Department")["Salary"].sum()

Department
HR           175
IT           163
Marketing    180
Sales        155
Name: Salary, dtype: int64

In [28]:
df.groupby("Department")["Salary"].min()

Department
HR           85
IT           78
Marketing    88
Sales        75
Name: Salary, dtype: int64

In [29]:
df.groupby("Department")["Salary"].max()

Department
HR           90
IT           85
Marketing    92
Sales        80
Name: Salary, dtype: int64

In [30]:
df.groupby("Department")["Salary"].count()

Department
HR           2
IT           2
Marketing    2
Sales        2
Name: Salary, dtype: int64

In [31]:
df.groupby("Department")[["Salary","Age"]].sum()

            Salary  Age
Department
HR             175   48
IT             163   52
Marketing      180   54
Sales          155   48

In [32]:
df.groupby("Department")[["Salary","Age","Gender"]].max()

            Salary  Age Gender
Department
HR              90   25      M
IT              85   30      M
Marketing       92   28      M
Sales           80   27      F

In [33]:
df.groupby("Department")[["Salary","Age","Gender"]].min()

            Salary  Age Gender
Department
HR              85   23      F
IT              78   22      M
Marketing       88   26      F
Sales           75   21      F

In [34]:
df.groupby(["Department","Gender"])[["Salary","Age","Gender"]].max()

                   Salary  Age Gender
Department Gender
HR         F           90   25      F
           M           85   23      M
IT         M           85   30      M
Marketing  F           88   26      F
           M           92   28      M
Sales      F           80   27      F

In [39]:
df.groupby(["Department","Gender"])[["Salary","Age","JoinDate"]].count()

                   Salary  Age  JoinDate
Department Gender
HR         F            1    1         1
           M            1    1         1
IT         M            2    2         2
Marketing  F            1    1         1
           M            1    1         1
Sales      F            2    2         2

In [41]:
df.groupby(["Team","Department"])["Salary"].mean()

Team  Department
A     HR            87.5
B     IT            81.5
C     Marketing     90.0
D     Sales         80.0
Name: Salary, dtype: float64

In [43]:
type(df.groupby(["Team","Department"])["Salary"].mean())

pandas.Series

__Aggregate__

.agg and .aggregate are same . Both of them return DataFrame

In [44]:
df.groupby(["Department"])["Salary"].agg(["mean","max","count"])

            mean  max  count
Department
HR          87.5   90      2
IT          81.5   85      2
Marketing   90.0   92      2
Sales       80.0   80      2

In [45]:
df.groupby(["Department"])["Salary"].agg(["mean","max","min","count","sum"])

            mean  max  min  count  sum
Department
HR          87.5   90   85      2  175
IT          81.5   85   78      2  163
Marketing   90.0   92   88      2  180
Sales       80.0   80   80      2  160

**Filter**

In [46]:
df.groupby(["Department"]).filter(lambda x : x ["Salary"].mean() >85)

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25

**Transform**

adds a new column with the returned value of groupby

In [47]:
df["Mean_Salary"]=df.groupby(["Department"])["Salary"].transform("mean")

In [48]:
df

  Department Team Gender  Salary  Age   JoinDate  Mean_Salary
0         HR    A      M      85   23 2020-01-10         87.5
1         HR    A      F      90   25 2020-02-15         87.5
2         IT    B      M      78   30 2021-03-20         81.5
3         IT    B      M      85   22 2021-04-10         81.5
4  Marketing    C      M      92   28 2020-05-30         90.0
5  Marketing    C      F      88   26 2020-06-25         90.0
6      Sales    D      F      80   21 2021-07-15         80.0
7      Sales    D      F      80   27 2021-08-01         80.0

In [49]:
df["Avg_Gender_Age"]=df.groupby(["Gender"])["Age"].transform("mean")
df

  Department Team Gender  Salary  Age   JoinDate  Mean_Salary  Avg_Gender_Age
0         HR    A      M      85   23 2020-01-10         87.5           25.75
1         HR    A      F      90   25 2020-02-15         87.5           24.75
2         IT    B      M      78   30 2021-03-20         81.5           25.75
3         IT    B      M      85   22 2021-04-10         81.5           25.75
4  Marketing    C      M      92   28 2020-05-30         90.0           25.75
5  Marketing    C      F      88   26 2020-06-25         90.0           24.75
6      Sales    D      F      80   21 2021-07-15         80.0           24.75
7      Sales    D      F      80   27 2021-08-01         80.0           24.75

In [51]:
df["Max_Dept_Salary"]=df.groupby(["Department"])["Salary"].transform("max")
df

,Department,Team,Gender,Salary,Age,JoinDate,Mean_Salary,Avg_Gender_Age,Max_Dept_Salary
0,HR,A,M,85,23,2020-01-10,87.5,25.75,90
1,HR,A,F,90,25,2020-02-15,87.5,24.75,90
2,IT,B,M,78,30,2021-03-20,81.5,25.75,85
3,IT,B,M,85,22,2021-04-10,81.5,25.75,85
4,Marketing,C,M,92,28,2020-05-30,90.0,25.75,92
5,Marketing,C,F,88,26,2020-06-25,90.0,24.75,92
6,Sales,D,F,80,21,2021-07-15,80.0,24.75,80
7,Sales,D,F,80,27,2021-08-01,80.0,24.75,80