# **Merge and Joining**

In [1]:
import pandas as pd

In [11]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})
managers = pd.DataFrame({
    "DeptID": [10, 30, 40,70],
    "Name": ["Ankit", "Abhishek", "Prachi","Sneha"]
})

In [12]:
# InnerJoin
pd.merge(employees,departments,on="DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [13]:
# LeftJoin
pd.merge(employees,departments,on="DeptID", how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [14]:
# RightJoin
pd.merge(employees,departments,on="DeptID",how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [30]:
# OuterJoin
pd.merge(employees,managers,on="DeptID",how="outer")

   EmpID   Name_x  DeptID    Name_y
0    1.0    Alice      10     Ankit
1    2.0      Bob      20       NaN
2    3.0  Charlie      30  Abhishek
3    NaN      NaN      40    Prachi
4    NaN      NaN      70     Sneha

In [33]:
pd.merge(employees,departments,on="DeptID",how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [19]:
df2=pd.merge(managers,pd.merge(employees,departments,on="DeptID"),on="DeptID",how="right")
df2

   DeptID Name_x  EmpID Name_y     DeptName
0      10  Ankit      1  Alice           HR
1      20    NaN      2    Bob  Engineering

In [28]:
df2.rename(columns={"Name_x":"Manager Name"},inplace=True)

In [29]:
df2

   DeptID Manager Name  EmpID Name_y     DeptName
0      10        Ankit      1  Alice           HR
1      20          NaN      2    Bob  Engineering

## **Concatination**

In [41]:
df3=pd.DataFrame({
        "Name":["Abhishek","Rahul","Barsha"],
        "Age":[21,20,21]
})
df4=pd.DataFrame({
        "Name":["Anshika","Gaurav","Ankita"],
        "Salary":[8,7,10]
})
df5=pd.DataFrame({
        "Name":["Ashish","Ankita","Sahad"],
        "Age":[22,20,21]
})

In [42]:
df3

       Name  Age
0  Abhishek   21
1     Rahul   20
2    Barsha   21

In [43]:
df4

      Name  Salary
0  Anshika       8
1   Gaurav       7
2   Ankita      10

In [44]:
pd.concat([df3,df4])

       Name   Age  Salary
0  Abhishek  21.0     NaN
1     Rahul  20.0     NaN
2    Barsha  21.0     NaN
0   Anshika   NaN     8.0
1    Gaurav   NaN     7.0
2    Ankita   NaN    10.0

In [45]:
pd.concat([df3,df4,df5])

       Name   Age  Salary
0  Abhishek  21.0     NaN
1     Rahul  20.0     NaN
2    Barsha  21.0     NaN
0   Anshika   NaN     8.0
1    Gaurav   NaN     7.0
2    Ankita   NaN    10.0
0    Ashish  22.0     NaN
1    Ankita  20.0     NaN
2     Sahad  21.0     NaN

In [48]:
df7=pd.concat([df3,df4,df5])
df7.sort_index()

       Name   Age  Salary
0  Abhishek  21.0     NaN
0   Anshika   NaN     8.0
0    Ashish  22.0     NaN
1     Rahul  20.0     NaN
1    Ankita  20.0     NaN
1    Gaurav   NaN     7.0
2    Barsha  21.0     NaN
2    Ankita   NaN    10.0
2     Sahad  21.0     NaN

axis=1 for width concatination by making new columns

In [40]:
pd.concat([df3,df4],axis=1)

       Name  Age     Name  Salary
0  Abhishek   21  Anshika       8
1     Rahul   20   Gaurav       7
2    Barsha   21   Ankita      10

In [47]:
df6=pd.concat([df3,df4,df5],axis=1)
df6

       Name  Age     Name  Salary    Name  Age
0  Abhishek   21  Anshika       8  Ashish   22
1     Rahul   20   Gaurav       7  Ankita   20
2    Barsha   21   Ankita      10   Sahad   21