**creating DataFrames from different datastructures**

In [7]:
import pandas as pd

**from list**

In [2]:
#from list
a=[["a",99,100,98],["b",45,90,23],["c",56,87,24]]
df=pd.DataFrame(a)
df

   0   1    2   3
0  a  99  100  98
1  b  45   90  23
2  c  56   87  24

In [6]:
b=pd.DataFrame(a,columns=["name","physics","chemistry","maths"])
b

  name  physics  chemistry  maths
0    a       99        100     98
1    b       45         90     23
2    c       56         87     24

**from dictionary**

In [8]:
dict={"abhishek":[99,98,100],"sneha":[34,42,32],"barsha":[80,87,67]}
df2=pd.DataFrame(dict)
df2

   abhishek  sneha  barsha
0        99     34      80
1        98     42      87
2       100     32      67

In [16]:
dic3={"name":["abhishek","sneha","barsha"],"physics":[99,38,70],"chemistry":[98,42,82],"maths":[100,57,87]}
df3=pd.DataFrame(dic3)
df3

       name  physics  chemistry  maths
0  abhishek       99         98    100
1     sneha       38         42     57
2    barsha       70         82     87

**from numpy array**

In [18]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[4,3,2]])
df4=pd.DataFrame(arr ,  columns=["a","b","c"])
df4

   a  b  c
0  1  2  3
1  4  5  6
2  4  3  2

**from excel**

In [3]:
df5=pd.read_excel("Book2.xlsx")
df5

   S.NO PARTY NAME  CONTENT
0     1          D     1212
1     2          M      121
2     3          B      123
3     4          L      456
4     5          P      658
5     6          U      789
6     7          T      987
7     8         Y4      654
8     9          1      321

In [4]:
df6=pd.read_excel("data.xlsx")
df6

       name  aptitude  interview  DSA  project  skills
0  abhishek        10         10   10       10      10
1     sneha         1          5    2        6       4
2    barsha         8          9    8        9       7
3      amit         6          9    5        7       5
4   anshika         8          6    2        6       2
5     kirti         5          5    6        5       6
6     rahul         6          2    3        4       4
7    ishika         2          7    5        6       6

**from csv file**

In [5]:
df7=pd.read_csv("data2.csv")
df7

       name  aptitude  interview  DSA  project  skills
0  abhishek        10         10   10       10      10
1     sneha         1          5    2        6       4
2    barsha         8          9    8        9       7
3      amit         6          9    5        7       5
4   anshika         8          6    2        6       2
5     kirti         5          5    6        5       6
6     rahul         6          2    3        4       4
7    ishika         2          7    5        6       6

**from json file**

In [15]:
df9 = pd.read_json("data3.json")
df9

,employee_id,name,age,department,designation,salary,email,city,skills,is_active
0,EMP001,Rahul Sharma,28,Engineering,Software Engineer,75000,rahul.sharma@example.com,Mumbai,"[Python, SQL, Git]",True
1,EMP002,Priya Singh,32,Marketing,Marketing Manager,85000,priya.singh@example.com,Delhi,"[SEO, Content Marketing, Analytics]",True
2,EMP003,Amit Verma,25,Engineering,Frontend Developer,68000,amit.verma@example.com,Bangalore,"[JavaScript, React, CSS]",True
3,EMP004,Sneha Gupta,30,HR,HR Executive,55000,sneha.gupta@example.com,Pune,"[Recruitment, Communication]",True
4,EMP005,Karan Mehta,35,Finance,Financial Analyst,92000,karan.mehta@example.com,Chennai,"[Excel, Power BI, Accounting]",False
5,EMP006,Neha Kapoor,27,Engineering,Backend Developer,80000,neha.kapoor@example.com,Hyderabad,"[Java, Spring Boot, MongoDB]",True
6,EMP007,Vikas Yadav,29,Sales,Sales Executive,60000,vikas.yadav@example.com,Lucknow,"[Negotiation, CRM]",True
7,EMP008,Anjali Roy,31,Engineering,Data Analyst,78000,anjali.roy@example.com,Kolkata,"[Python, Pandas, Tableau]",True

**from url**

In [16]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df10=pd.read_csv(url)
df10

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [17]:
df10[70:80]

    total_bill   tip     sex smoker   day    time  size
70       12.02  1.97    Male     No   Sat  Dinner     2
71       17.07  3.00  Female     No   Sat  Dinner     3
72       26.86  3.14  Female    Yes   Sat  Dinner     2
73       25.28  5.00  Female    Yes   Sat  Dinner     2
74       14.73  2.20  Female     No   Sat  Dinner     2
75       10.51  1.25    Male     No   Sat  Dinner     2
76       17.92  3.08    Male    Yes   Sat  Dinner     2
77       27.20  4.00    Male     No  Thur   Lunch     4
78       22.76  3.00    Male     No  Thur   Lunch     2
79       17.29  2.71    Male     No  Thur   Lunch     2

**EDA exploratory Data Analysis**

In [18]:
df10.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [20]:
df10.shape

(244, 7)

In [21]:
# first 5 rows
df10.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [22]:
# last 5 rows
df.tail()

,employee_id,name,age,department,designation,salary,email,city,skills,is_active
3,EMP004,Sneha Gupta,30,HR,HR Executive,55000,sneha.gupta@example.com,Pune,"[Recruitment, Communication]",True
4,EMP005,Karan Mehta,35,Finance,Financial Analyst,92000,karan.mehta@example.com,Chennai,"[Excel, Power BI, Accounting]",False
5,EMP006,Neha Kapoor,27,Engineering,Backend Developer,80000,neha.kapoor@example.com,Hyderabad,"[Java, Spring Boot, MongoDB]",True
6,EMP007,Vikas Yadav,29,Sales,Sales Executive,60000,vikas.yadav@example.com,Lucknow,"[Negotiation, CRM]",True
7,EMP008,Anjali Roy,31,Engineering,Data Analyst,78000,anjali.roy@example.com,Kolkata,"[Python, Pandas, Tableau]",True

In [23]:
# the most important gives necessary statistical dat of given data
df.describe()

             age        salary
count   8.000000      8.000000
mean   29.625000  74125.000000
std     3.113909  12483.560618
min    25.000000  55000.000000
25%    27.750000  66000.000000
50%    29.500000  76500.000000
75%    31.250000  81250.000000
max    35.000000  92000.000000

In [25]:
# gives the info of of each columns data type and storage
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  8 non-null      str
 1   name         8 non-null      str
 2   age          8 non-null      int64
 3   department   8 non-null      str
 4   designation  8 non-null      str
 5   salary       8 non-null      int64
 6   email        8 non-null      str
 7   city         8 non-null      str
 8   skills       8 non-null      object
 9   is_active    8 non-null      bool
dtypes: bool(1), int64(2), object(1), str(6)
memory usage: 716.0+ bytes